"""empty message

Revision ID: 24b5eda1ac01
Revises: 
Create Date: 2019-02-15 18:00:32.224904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b5eda1ac01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paygrade', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paygrade')
    )
    op.add_column(u'employees', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column(u'employees', 'grade_id')
    op.drop_table('grades')
    # ### end Alembic commands ###
